Fix buggy md syntax in technical-overview.md (#221)
## Ticket

Resolves linter complaint:
```
  ERROR: 1 dead links found!
  [✖] alembic-src → Status: 400
```

## Changes

Use square brackets, not parentheses.

## Context for reviewers

> Testing instructions, background context, more in-depth details of the
implementation, and anything else you'd like to call out or ask
reviewers.

## Testing

The markdown linter should not cause this error.